# Generated by Django 5.0.1 on 2024-02-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesMedicasTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImagenesMedicasTiposNombre', models.CharField(choices=[('Rayos X', 'Rayos X'), ('Scanner', 'Scanner'), ('Tomograficas', 'Tomograficas'), ('Resonancia Magnetica', 'Resonancia Magnetica')], max_length=100)),
                ('ImagenesMedicasTiposActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PacientesNombre', models.CharField(max_length=100, verbose_name='Pacientes')),
                ('PacientesApellido', models.CharField(max_length=100)),
                ('PacientesDireccion', models.CharField(max_length=100)),
                ('PacientesTelefono', models.CharField(max_length=10)),
                ('PacientesEmail', models.CharField(max_length=100)),
                ('PacientesEmailNormalizado', models.CharField(max_length=100)),
                ('PacientesActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='ImagenesMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImagenesMedicasTiposDescripcion', models.CharField(max_length=200)),
                ('ImagenesMedicas_Img', models.ImageField(upload_to='ImagenesMedicas')),
                ('ImagenesMedicas_Tipos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.imagenesmedicastipos')),
                ('ImagenesMedicas_PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.Pacientes')),
            ],
            options={
                'verbose_name_plural': 'Imagenes Medicas',
            },
        ),
    ]
