# Generated by Django 5.0 on 2024-02-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0003_dentistas_tratamientos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentistas',
            name='DentistasActivo',
        ),
    ]
