# Generated by Django 5.0 on 2024-03-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_tratamientos_nombre_tratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='Paciente_id_foreign_key',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='Tratamiento_Paciente_id',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='dentista',
        ),
    ]
