# Generated by Django 5.0.3 on 2024-04-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0007_historial_paciente_id_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(verbose_name='Fecha y Hora')),
                ('HoraInicio', models.TimeField(verbose_name='Hora Inicio')),
                ('HoraFin', models.TimeField(verbose_name='Hora Fin')),
                ('Status', models.BooleanField(default=True, verbose_name='Activo')),
                ('Confirmada', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('Dentistas_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.dentistas')),
                ('Pacientes_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.pacientes')),
                ('TipoTratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.tratamientopaciente')),
            ],
            options={
                'verbose_name_plural': 'Agenda',
            },
        ),
    ]
