# Generated by Django 5.0.3 on 2024-04-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0008_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='HoraFin',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='HoraInicio',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='Fecha',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='TipoTratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.tratamientos'),
        ),
    ]
