# Generated by Django 5.0 on 2024-02-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('dentista_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_dentista')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido1', models.CharField(max_length=255, verbose_name='apellido1')),
                ('apellido2', models.CharField(max_length=255, verbose_name='apellido2')),
                ('especialidad', models.CharField(max_length=255, verbose_name='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_paciente')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido1', models.CharField(max_length=255, verbose_name='apellido1')),
                ('apellido2', models.CharField(max_length=255, verbose_name='apellido2')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(max_length=255, verbose_name='direccion')),
                ('numero_telefono', models.IntegerField(verbose_name='numero_telefono')),
                ('e_mail', models.CharField(max_length=255, verbose_name='e_mail')),
            ],
        ),
    ]
