# Generated by Django 5.0 on 2024-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_dentista_e_mail_dentista_e_mail_normalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='numero_telefono',
            field=models.IntegerField(null=True, verbose_name='numero_telefono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_telefono',
            field=models.IntegerField(null=True, verbose_name='numero_telefono'),
        ),
    ]
