# Generated by Django 5.0.1 on 2024-02-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_dentista_numero_telefono_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dentista',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
