# Generated by Django 5.0.1 on 2024-02-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MetodosPagoNombre', models.CharField(max_length=100, verbose_name='Metodo de Pago')),
                ('MetodosPagoActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Metodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacturasFechaFactura', models.DateField()),
                ('Facturas_Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FacturasDetalle', models.CharField(max_length=300)),
                ('Facturas_PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.Pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PagosNombre', models.CharField(max_length=100)),
                ('PagosFechaPago', models.DateField()),
                ('Pagos_Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PagosActivo', models.BooleanField(default=True)),
                ('Pagos_PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pacientes.Pacientes')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
