# Generated by Django 5.0.1 on 2024-02-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetodosPago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturas',
            options={'verbose_name_plural': 'Facturas'},
        ),
    ]
